name: "🔖 Roadmap Item"
description: New feature idea
title: "[ROADMAP] <short description>"
labels: [type:"roadmap"]
projects: ["GLB-ATOS-MSCC/16", "GLB-ATOS-MSCC/31"]

body:
  - type: markdown
    attributes:
      value: |
        Help us understand your idea better.

  - type: input
    id: summary
    attributes:
      label: Feature summary
      placeholder: e.g. "Provide new hyperscaler support"
    validations:
      required: false

  - type: textarea
    id: motivation
    attributes:
      label: Why is this needed?
      placeholder: Describe the business or technical value
    validations:
      required: false
